=== axrt/TUIT/src/io/properties/jaxb/properties.dtd
<!ELEMENT TUITProperties (DBConnection,BLASTNPath,TMPDir,BLASTNParameters,SpecificationParameters*)>
        <!ELEMENT DBConnection ANY>
        <!ATTLIST DBConnection url CDATA #REQUIRED login CDATA #REQUIRED password CDATA #REQUIRED>
        <!ELEMENT BLASTNPath ANY>
        <!ATTLIST BLASTNPath path CDATA #REQUIRED>
        <!ELEMENT TMPDir ANY>
        <!ATTLIST TMPDir path CDATA #REQUIRED>
        <!ELEMENT BLASTNParameters (Database*, Expect, EntrezQuery, Remote, MaxFilesInBatch)>
        <!ELEMENT Database ANY>
        <!ATTLIST Database use (nt|est) #REQUIRED>
        <!ELEMENT Expect ANY>
        <!ATTLIST Expect value CDATA #REQUIRED>
        <!ELEMENT EntrezQuery ANY>
        <!ATTLIST EntrezQuery value CDATA #REQUIRED>
        <!ELEMENT Remote ANY>
        <!ATTLIST Remote deligate (yes|no) #REQUIRED>
        <!ELEMENT MaxFilesInBatch ANY>
        <!ATTLIST MaxFilesInBatch value CDATA #REQUIRED>
        <!ELEMENT SpecificationParameters (CutoffSet)>
        <!ELEMENT CutoffSet (pIdentCutoff,QueryCoverageCutoff,EvalueRatioCutoff)>
        <!ATTLIST CutoffSet rank (root_of_life | no_rank | superkingdom | kingdom | subkingdom | superphylum | phylum | subphylum | superclass | c_lass | subclass |infraclass | superorder | order | suborder | infraorder | parvorder | superfamily | family | subfamily | tribe | subtribe | genus | subgenus | species_group | species_subgroup | species | subspecies | varietas | forma ) #REQUIRED>
        <!ELEMENT pIdentCutoff ANY>
        <!ATTLIST pIdentCutoff value CDATA #REQUIRED>
        <!ELEMENT QueryCoverageCutoff ANY>
        <!ATTLIST QueryCoverageCutoff value CDATA #REQUIRED>
        <!ELEMENT EvalueRatioCutoff ANY>
        <!ATTLIST EvalueRatioCutoff value CDATA #REQUIRED>

=== axrt/TUIT/testing/test/properties.xml
<?xml version="1.0"?>
<!DOCTYPE TUITProperties PUBLIC "-//TUIT//TUITProperties/EN" "properties.dtd">
<TUITProperties>
    <DBConnection url="localhost" login="tuit" password="tuit"/>
    <BLASTNPath path="/bin/blastn"/>
    <TMPDir path="/home/alext/Downloads/tmp"/>
    <BLASTNParameters>
        <Database use="nt"/>
        <Expect value="1.0"/>
        <EntrezQuery value="bacteria not hybrid not other not uncultured not enrichment not unclassified not uncultivated not unspecified not environmental not metagenomes"/>
        <Remote delegate="yes"/>
        <MaxFilesInBatch value="50"/>
    </BLASTNParameters>
    <!--Higher Level-->
    <SpecificationParameters>
        <CutoffSet rank="superkingdom">
            <pIdentCutoff value="60"/>
            <QueryCoverageCutoff value="80"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="kingdom">
            <pIdentCutoff value="60"/>
            <QueryCoverageCutoff value="80"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="superphylum">
            <pIdentCutoff value="60"/>
            <QueryCoverageCutoff value="80"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="phylum">
            <pIdentCutoff value="60"/>
            <QueryCoverageCutoff value="80"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="subphylum">
            <pIdentCutoff value="60"/>
            <QueryCoverageCutoff value="80"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="superclass">
            <pIdentCutoff value="60"/>
            <QueryCoverageCutoff value="80"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="infraclass">
            <pIdentCutoff value="60"/>
            <QueryCoverageCutoff value="80"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="c_lass">
            <pIdentCutoff value="60"/>
            <QueryCoverageCutoff value="80"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="subclass">
            <pIdentCutoff value="60"/>
            <QueryCoverageCutoff value="80"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <!--Order Level-->
    <SpecificationParameters>
        <CutoffSet rank="infraorder">
            <pIdentCutoff value="80"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="parvorder">
            <pIdentCutoff value="70"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="superorder">
            <pIdentCutoff value="70"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="order">
            <pIdentCutoff value="70"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="suborder">
            <pIdentCutoff value="70"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <!--Family Level-->
    <SpecificationParameters>
        <CutoffSet rank="superfamily">
            <pIdentCutoff value="80"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="family">
            <pIdentCutoff value="80"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="subfamily">
            <pIdentCutoff value="80"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="tribe">
            <pIdentCutoff value="80"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="subtribe">
            <pIdentCutoff value="80"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <!--Genus Level-->
    <SpecificationParameters>
        <CutoffSet rank="genus">
            <pIdentCutoff value="95"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="subgenus">
            <pIdentCutoff value="95"/>
            <QueryCoverageCutoff value="90"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <!--Species Level-->
    <SpecificationParameters>
        <CutoffSet rank="species_group">
            <pIdentCutoff value="97.5"/>
            <QueryCoverageCutoff value="95"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="species_subgroup">
            <pIdentCutoff value="97.5"/>
            <QueryCoverageCutoff value="95"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="species">
            <pIdentCutoff value="97.5"/>
            <QueryCoverageCutoff value="95"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="subspecies">
            <pIdentCutoff value="97.5"/>
            <QueryCoverageCutoff value="95"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="varietas">
            <pIdentCutoff value="97.5"/>
            <QueryCoverageCutoff value="95"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <SpecificationParameters>
        <CutoffSet rank="forma">
            <pIdentCutoff value="97.5"/>
            <QueryCoverageCutoff value="95"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
    <!-- -->
</TUITProperties>

=== axrt/TUIT/src/test/properties.xml
<?xml version="1.0"?>
<!DOCTYPE TUITProperties PUBLIC "-//TUIT//TUITProperties/EN" "properties.dtd">
<TUITProperties>
    <DBConnection url="localhost" login="ocular" password="ocular"/>
    <BLASTNPath path="/usr/bin/blastn"/>
    <TMPDir path="/home/alext/Downloads/tmp"/>
    <BLASTNParameters>
        <Database use="nt"/>
        <Expect value="10"/>
        <EntrezQuery value="not uncultured not enrichment not unclassified not uncultivated not unspecified"/>
        <Remote deligate="yes"/>
        <MaxFilesInBatch value="1"/>
    </BLASTNParameters>
    <SpecificationParameters>
        <CutoffSet rank="species">
            <pIdentCutoff value="97.5"/>
            <QueryCoverageCutoff value="95"/>
            <EvalueRatioCutoff value="100"/>
        </CutoffSet>
    </SpecificationParameters>
</TUITProperties>
